import express from 'express';
import AccommodationRoutes from 'src/modules/accommodation/accommodation.routes';
import LeaveRoutes from 'src/modules/leave/leave.routes';
import { AuthRoutes } from 'src/modules/auth/auth.routes';
import DepartmentRoutes from 'src/modules/department/department.routes';
import EmployeeRoutes from 'src/modules/employee/employee.routes';
import OrganizationRoutes from 'src/modules/organization/organization.routes';
import PermissionRoute from 'src/modules/permission/permission.routes';
import TemplateRoutes from 'src/modules/template/template.routes';
import AppraisalRoutes from 'src/modules/appraisal/appraisal.routes';
import PromotionRoutes from 'src/modules/promotion/promotion.routes';
import DisciplineRoutes from 'src/modules/discipline/discipline.routes';
import RetirementRoutes from 'src/modules/retirement/retirement.routes';
import RetrenchmentRoutes from 'src/modules/retrenchment/retrenchment.routes';
import TransferRoutes from 'src/modules/transfer/transfer.routes';
import CampMeetingRoute from 'src/modules/campMeeting/campMeeting.routes';
import AnalyticsRoutes from 'src/modules/analytics/analytics.routes';
import NotificationRoutes from 'src/modules/notification/notification.routes';
import MessageRoutes from 'src/modules/message/message.routes';
import FileIndexRoutes from 'src/modules/fileIndex/fileIndex.routes';

export const Routes = express.Router();

Routes.use(AuthRoutes);
Routes.use(DepartmentRoutes);
Routes.use(OrganizationRoutes);
Routes.use(EmployeeRoutes);
Routes.use(PermissionRoute);
Routes.use(AccommodationRoutes);
Routes.use(TemplateRoutes);
Routes.use(LeaveRoutes);
Routes.use(AppraisalRoutes);
Routes.use(PromotionRoutes);
Routes.use(DisciplineRoutes);
Routes.use(RetirementRoutes);
Routes.use(TransferRoutes);
Routes.use(RetrenchmentRoutes);
Routes.use(CampMeetingRoute);
Routes.use(AnalyticsRoutes);
Routes.use(NotificationRoutes);
Routes.use(MessageRoutes);
Routes.use(FileIndexRoutes);
