import express from 'express';
import LeaveRoutes from '@/modules/leave/leave.routes';
import AccommodationRoutes from '@/modules/accommodation/accommodation.routes';
import { AuthRoutes } from '@/modules/auth/auth.routes';
import DepartmentRoutes from '@/modules/department/department.routes';
import EmployeeRoutes from '@/modules/employee/employee.routes';
import OrganizationRoutes from '@/modules/organization/organization.routes';
import PermissionRoute from '@/modules/permission/permission.routes';
import TemplateRoutes from '@/modules/template/template.routes';
import AppraisalRoutes from '@/modules/appraisal/appraisal.routes';
import PromotionRoutes from '@/modules/promotion/promotion.routes';
import DisciplineRoutes from '@/modules/discipline/discipline.routes';
import RetirementRoutes from '@/modules/retirement/retirement.routes';
import RetrenchmentRoutes from '@/modules/retrenchment/retrenchment.routes';
import TransferRoutes from '@/modules/transfer/transfer.routes';
import CampMeetingRoute from '@/modules/campMeeting/campMeeting.routes';
import AnalyticsRoutes from '@/modules/analytics/analytics.routes';
import NotificationRoutes from '@/modules/notification/notification.routes';
import MessageRoutes from '@/modules/message/message.routes';
import FileIndexRoutes from '@/modules/fileIndex/fileIndex.routes';

export const Routes = express.Router();

Routes.use(AuthRoutes);
Routes.use(DepartmentRoutes);
Routes.use(OrganizationRoutes);
Routes.use(EmployeeRoutes);
Routes.use(PermissionRoute);
Routes.use(AccommodationRoutes);
Routes.use(TemplateRoutes);
Routes.use(LeaveRoutes);
Routes.use(AppraisalRoutes);
Routes.use(PromotionRoutes);
Routes.use(DisciplineRoutes);
Routes.use(RetirementRoutes);
Routes.use(TransferRoutes);
Routes.use(RetrenchmentRoutes);
Routes.use(CampMeetingRoute);
Routes.use(AnalyticsRoutes);
Routes.use(NotificationRoutes);
Routes.use(MessageRoutes);
Routes.use(FileIndexRoutes);
